# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Evan James Martin
tagline:             'Computer Science & Statistics'
description:         'Student at University of British Columbia, Vancouver, BC.'
baseurl:             '/blog/'
paginate:            5

# Custom vars
version:             1.0.0
