# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               evmarts
tagline:             'blog'
description:         'data science stuff'
baseurl:             '/blog'
paginate:            5

include:
  - "_img"

# Custom vars
version:             1.0.0
