# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               EJM
tagline:             'blog'
description:         ''
baseurl:             '/blog'
paginate:            5

include:
  - "_img"

# Custom vars
version:             1.0.0
